default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Authenticate with App Store Connect using P8 Auth Key
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true # We will provide the P8 file as a base64 string
    )

    # Optimization: Only build the specific iOS framework needed for the App Store (Arm64 Release)
    # This prevents building Android and Simulator binaries which saves ~15-20 minutes on CI.
    sh("cd ../.. && ./gradlew :shared:linkReleaseFrameworkIosArm64")

    # Disable automatic signing for CI
    # In some fastlane versions the project path is relative to the iosApp directory
    disable_automatic_code_signing(path: "iosApp.xcodeproj")

    # Build and upload
    build_app(
      scheme: "iosApp",
      project: "iosApp.xcodeproj",
      include_bitcode: false,
      export_method: "app-store",
      clean: true,
      export_options: {
        provisioningProfiles: {
          "com.arturshamsi.maxlift" => ENV["PROVISIONING_PROFILE_NAME"]
        }
      },
      xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{ENV["PROVISIONING_PROFILE_NAME"]}'"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
